services:

  front-envoy:
    image: envoy-ext_authz
    depends_on:
      upstream-service:
        condition: service_healthy
    environment:
    - FRONT_ENVOY_YAML
    ports:
    - "${PORT_PROXY:-8000}:8000"
    volumes:
    - ./etc/envoy/certs:/etc/envoy/certs
    - ./config/v3.yaml:/etc/envoy-config/v3.yaml


  ext_authz-grpc-service:
    image: authserver
    command: oidc --config=/etc/auth0-odic.yaml
    volumes:
    - ./auth0-odic.yaml:/etc/auth0-odic.yaml

  upstream-service:
    image: aiohttp-service
    volumes:
    - ./upstream/service/service.py:/code/service.py
